import React from "react";
import FormField from "../components/FormField";
import { useState } from "react";
import Loader from "../components/Loader";
const HomePage = () => {
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts] = useState(null);
    const [searchText, setSearchText] = useState("dsf");

    return (
        <section>
        <div>
            <h1 className="font-extrabold text-[32px]">The Community Showcase</h1>
            <p className="mt-2 max-w-[700px] text-slate-500">
            Brose through a collection of imaginative and visually stunning images
            generated by DALL-E AI
            </p>
        </div>
        <div className="mt-16">
            <FormField label={"search"} className="border-1" />
        </div>

        <div className="mt-10">
            {loading ? (
            <div className="flex justify-center items-center">
                <Loader />
            </div>
            ) : (
            <>
                {searchText && (
                <h2 className="font-medium text-xl mb-3">
                    Showing Results for <span className="">{searchText}</span>
                </h2>
                )}

                <div className="grid grid-cols-1 lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2"></div>
            </>
            )}
        </div>
        </section>
  );
};

export default HomePage;
